### ISSUE TITLE
Validation Rule: Ensure all "type" properties have appropriate values

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/oai-ts-core#10]
Many places in the spec require a "type" property, for example in the Schema object.  We should make sure that the value of this property is one of the possible values.

**Comment by kand617** [comment]
I would like to take a shot at this issue. 
I have forked and will ping when ready!

**Comment by EricWittmann** [comment]
Nice!  One thing about adding new validation rules is that every violation needs a unique identifier.  Just go ahead and make something up as a placeholder and I'll update it with something final when I merge the PR.

**Comment by EricWittmann** [comment]
Aaaaand I see you've already done it!  lol 

Very nice.  I'll review and merge asap.

**Comment by kand617** [comment]
@EricWittmann I see it has been merged. Can we close the issue?

**Comment by EricWittmann** [comment]
Yep, sorry.  Assumed you had a "Fixes #10" in the commit message that would have auto-closed this on merge.  My bad.  Closing now.

Thanks for the contribution!

**Comment by kand617** [comment]
Ah did not know it worked that way ^^
