### ISSUE TITLE
Error while using NPM module

### ISSUE THREAD

**Issue by BabuGiri** [Apicurio/oai-ts-core#11]
Hi i am trying to use oai-ts-core node module from npm with sample to exercise module API's as per readme, but i am getting error "SyntaxError: Unexpected token export" any suggestion what would be the problem.

same i tried with https://npm.runkit.com/oai-ts-core assuming my environment may have some problem there also i see same error "SyntaxError: Unexpected token export"

please suggest if i am doing something wrong.

Thank you

**Comment by EricWittmann** [comment]
Hi there.

Alas I am not a node.js developer.  I'm using the oai-ts-core library in a couple of Angular web applications, but not in any node.js apps.  So I'm actually not sure how to package the library for use in node.js!

Googling the error message seems to imply that the module format (in this case UMD) is not compatible with the node.js environment.

If you know how to package a typescript library for use in a node.js environment, I would 100% welcome a change to the project to make that happen.

If the meantime, I'll see if I can find any obvious information about how to create a node.js library, and if it's easy enough to do I'll try to update the release to include node.js support. :)

**Comment by EricWittmann** [comment]
After a bit more research, it seems that the root problem is that I'm packaging the library as an ES6 module, and node.js can't load ES6 modules.  It can only handle commonjs modules.

I'm using rollup to bundle the various transpiled (via tsc) javascript files into a module, and rollup only does ES6. 

Building everything as a commonjs module should presumably be possible, but likely requires a separate build.  One where TSC is configured to target commonjs and then some *other* bundler is used to produce a commonjs module.

Again, I'm open to contributions to make this happen, and would be happy to maintain it once it's contributed.  But I'm not certain whether I'll find the time to do it myself...

**Comment by BabuGiri** [comment]
I am newbee to JS (node, angular) learning now some of the concepts, i need to explore more on ES6 and commonjs.

if you have some example on how this module can be used with angular JS that also helps i am not particular about Node.js, mainly looking to explore model with some of my JSON samples.

**Comment by EricWittmann** [comment]
There are a few options, in that case.  Here is the main project I'm using the library in (it's an Angular + Typescript web application):

https://github.com/Apicurio/apicurio-studio/tree/master/front-end/app

It's structured very much like a typical angular web application.  It uses npm/yarn to manage its dependencies (you'll see an entry in package.json for *oai-ts-core*).  

Note:  The *oai-ts-core* library ships with typescript definitions so it works very well in other typescript projects.

Another option you have, if you're not interested in a Typescript+Angular platform, is to simply use the *oai-ts-core* library in a simple javascript web app.  To do that, simply directly reference the *OAI.umd.js* in your index.html file (using a standard <script> tag).  The *OAI.umd.js* file can be found in the **node_modules/oai-ts-core/bundles** directory when you use npm or yarn to manage your JS dependencies.

If you take the standard JS route, then the documentation for how to use it is in the readme:

https://github.com/Apicurio/oai-ts-core/tree/master/module
