### ISSUE TITLE
 Schema Discriminator is only allowed when using one of: ["oneOf", "anyOf", "allOf"]

### ISSUE THREAD

**Issue by sherl0cks** [Apicurio/oai-ts-core#15]
This shows up in response to a [discriminator in a "base schema"](https://github.com/sherl0cks/explore-ddd-2018-demo/blob/73fda56da1ef32f0c7ad695df0734d3ed19e3ac2/sales/sales-app/src/main/resources/sales-open-api-spec.yaml#L165-L166), which I took as an example from the `Pet` schema in the `AllOf` section in https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/. 

Which one is correct?
![screenshot from 2018-07-18 12-04-40](https://user-images.githubusercontent.com/1335137/42899274-c7ab85ec-8a82-11e8-8c23-539f2b61d002.png)

**Comment by sherl0cks** [comment]
I must say that your self deprecating humor in github issues is top shelf, but no need to be so hard on yourself. Especially in this case, as to be honest, its a strange usage where the field shows up in the "base schema" and then all of the extensions that show up in request/response.

I wish there was a cleaner way to do the equivalent of defining an interface in Java and then using that in request / response definitions

**Comment by EricWittmann** [comment]
I try to be helpful, but when that doesn't work I can at least be funny.  Sometimes I'm both.  Then I take the afternoon off.

I also agree that JSON schema has some warts when we try to use it to model some Java data structures.  Everything is great when the beans are simple.  But it can get wonky fast.  I do wonder how this sort of thing is handled by the Generate Project feature in Apicurio.  I think you mentioned you may have tried it?  What happened?  I'm using a 3rd party library to convert the JSON schemas into Java beans.  I'm guessing it freaks out?

**Comment by sherl0cks** [comment]
Well I suspect you have a lot of free time in the afternoons then. 

Generating the project results in the subclass that do not extend the base class and also do not declare the properties themselves. So essential the info in the base class is lost for all subtypes.

**Comment by sherl0cks** [comment]
Seems there are various issues around this on swagger side too https://github.com/swagger-api/swagger-codegen/issues/358

**Comment by EricWittmann** [comment]
This might be a powerful use case that we could handle to differentiate.
