### ISSUE TITLE
Vendor extension is not resolved in Schema

### ISSUE THREAD

**Issue by tnngo2** [Apicurio/oai-ts-core#16]
I'd like to report an issue related to resolving vendor extension of a Schema Object.

OpenAPI doc:
```
...
components:
  schemas:
    EmailCollection:
      type: array
      items:
        $ref: '#/components/schemas/Email'
      x-is-restful-resource: false
    Email:
      type: object
      properties:
        Email:
          $ref: '#/components/schemas/Email'
```

**Expected**: 
schema.extensions() returns a array with one element named 'x-is-restful-resource' 

**Real Output**:
schema.extensions() returns undefined.

**Cause**:
The cause is due to the wrong argument passing in OasJS2ModelReader::readSchema()

Class: OasJS2ModelReader
Method: readSchema
Line of Code:
```
this.readExtensions(items, schemaModel);
```
should be 
```
this.readExtensions(schema, schemaModel);
```

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/oai-ts-core/pull/17 - thanks!  Also, unit tests added in https://github.com/Apicurio/oai-ts-core/commit/31ae640504e08f804519a94c2a8a6f4d9511811a

**Comment by EricWittmann** [comment]
Oh and by the way - I released a new version of `oai-ts-core` that contains your fix:

https://www.npmjs.com/package/oai-ts-core

fwiw :)

**Comment by tnngo2** [comment]
Thank you for the prompt action.
:+1:  for the npm release
