### ISSUE TITLE
Docs - createDocument() Input

### ISSUE THREAD

**Issue by kand617** [Apicurio/oai-ts-core#19]
Open API specifications can be either written in JSON or YAML. 
Currently it does not look like the library supports inputs based in YAML and only accepts JSON strings or JS objects.

The docs should be be updated accordingly

**Comment by kand617** [comment]
Oops, Just noticed it was further down....

![image](https://user-images.githubusercontent.com/5092518/46060125-8544cf80-c194-11e8-88fc-4c96f9aa87f8.png)

**Comment by EricWittmann** [comment]
Yeah - the reason I don't support YAML there is that it would require an external dependency, and I'm trying to keep this library dependency-free.  Obviously you can use a YAML parser to get a js object and then pass that in.

As you've probably noticed, that means there's no way to get the line number/text region of a particular node in the data model.

So if you're working on an independent OpenAPI validator and you want to highlight regions of the source YAML text based on validation errors found by this library, then the biggest challenge will be mapping the error back to something in the source.  I think this is a solvable problem, especially using the [NodePath](https://github.com/Apicurio/oai-ts-core/blob/master/src/models/node-path.ts#L28) class.  But it will likely be non-trivial.  :)  On the bright side, if that problem were solved, it would be a GREAT OSS contribution (either to this library or perhaps a new one) and would help address a [feature request in Apicurio](https://github.com/Apicurio/apicurio-studio/issues/336)).

**Comment by kand617** [comment]
Make sense. 
I think mapping error-> location would be an interesting problem to solve..... 
Not sure how accurate it can be, but wont know for sure till we take a crack at it.

**Comment by EricWittmann** [comment]
Certainly it's no harder than writing a parser that produces a JS object but also remembers the character ranges for all of the nodes. 

Oh wait...it's exactly that.  :)

I haven't looked, but I assume the swagger editor does this.  I wonder how....
