### ISSUE TITLE
CI - Add Circle CI Setup

### ISSUE THREAD

**Issue by kand617** [Apicurio/oai-ts-core#22]
As a developer I would like to have a CI system build/test my application. 
This is useful to ensure tests results are visible when creating PRs

Acceptance Criteria:
- Run Tests on each commit by Travis
- Update Readme with Travis build status badge

**Comment by EricWittmann** [comment]
We've been moving more to CircleCI - so I'll set up something there.

**Comment by kand617** [comment]
Sure, is circle CI ideal for open source projects? I was under the impression they were not free?

**Comment by EricWittmann** [comment]
Seems to be OK.  Pretty sure we wouldn't use it otherwise...

If I end up being wrong about that, then I'll switch over to Travis.

**Comment by kand617** [comment]
Oh Just saw you added it. Perhaps we can close this.
