### ISSUE TITLE
Code Style - TS Lint

### ISSUE THREAD

**Issue by kand617** [Apicurio/oai-ts-core#23]
It is good practice to have a tslint file to ensure code conforms to the style rules. 
This makes it very easy to do auto-formatting on save as well. 

I would recommend: https://github.com/alexjoverm/typescript-library-starter/blob/master/tslint.json

**Comment by kand617** [comment]
@EricWittmann, If we are in agreement, then I could work on a PR

**Comment by EricWittmann** [comment]
Yeah that'd be great.
