### ISSUE TITLE
Hosted Demo Page

### ISSUE THREAD

**Issue by kand617** [Apicurio/oai-ts-core#25]
As a end-user I would like to have a live demo environment.
This demo should have
- Text Area 
- Validation Errors

Perhaps a simple StackBlitz app

**Comment by kand617** [comment]
I made such a demo here :
https://oas-ts-core-demo.stackblitz.io

It could obviously look prettier.... but its a start I suppose

**Comment by EricWittmann** [comment]
Nice - how do I contribute to that?

**Comment by kand617** [comment]
https://stackblitz.com/edit/oas-ts-core-demo

**Comment by EricWittmann** [comment]
Ah... shows you how often I've used stackblitz. :)

Thanks!

**Comment by EricWittmann** [comment]
OK I've forked yours (didn't want to mess with it and am not sure I could have if I wanted to) and made some style improvements:

https://oai-ts-core-demo.stackblitz.io/

Let me know what you think and if you have any additional suggestions.

**Comment by kand617** [comment]
Looks much better! 
Lets add a link to this and the editor on the readme so that people can view/experiement

**Comment by EricWittmann** [comment]
Done.

**Comment by EricWittmann** [comment]
https://github.com/Apicurio/oai-ts-core/commit/58d25d1d9a6fd5414cc822c012ca2516c4ff6509
