### ISSUE TITLE
Validation Rule: Implement validation of operationId

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/oai-ts-core#7]
**Class**: Oas20InvalidPropertyValueValidationRule
**Method**: isValidOperationId

From the specification:

`Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.`

I think this implies that we should have a reqex validation for this to ensure it follows basic programming conventions e.g. camelCase.

**Comment by kand617** [comment]
Hmm I think as a tool, it should not enforce style. 
Alternatively we could perform linting as a separate function.

```
let library: OasLibraryUtils = new OasLibraryUtils();
library.lint(document, {
    customRule1:{....},
    customRule2:{....}
})

library.lint(document, OASLintPreset)
```

**Comment by EricWittmann** [comment]
Well, I'm not necessarily opposed to adding a "linting" concept.  However, one thing to note is that the validation problem severities can be modified by the caller.  The long-term goal of the library is to support custom severity reporting (so that validation problems that the caller doesn't really care about can be suppressed) *and* custom validation rules.

The former is already supported, the latter is not.

So in the long run I am hoping to have a large library of validation rules that can essentially be enabled/disabled.  We'll hopefully also be able to organize the rules into groups (perhaps each rule can be tagged) so that whole groups can be enabled/disabled.  Actually the severity granularity is greater than that - it's the standard error/warning/info/ignore idea.  

In Apicurio, the idea is that different users will likely care about different validation rules (or sets of rules) based on their role.  So e.g. tech writers might have a separate set of validation rules that deal primarily with summary/description issues.

**Comment by EricWittmann** [comment]
Oh - my point is that the above architecture supports having a set of validation rules that could be tagged with "lint" and then effectively disabled if desired.  For example.
